name: internal release gdb

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        description: 'What os?'
      attribute:
        required: true
        type: string
        description: 'What attribute?'

jobs:
  build-gdb:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 180
    environment:
      name: pypi
      url: https://pypi.org/p/gdb-for-pwndbg
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # @v3
    - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72  # @v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: mk dist
      run: |
        mkdir dist

    - name: build 310
      run: |
        nix build '.#${{ inputs.attribute }}.310' -o ./result
        cp ./result/*.whl ./dist/

    - name: build 311
      run: |
        nix build '.#${{ inputs.attribute }}.311' -o ./result
        cp ./result/*.whl ./dist/

    - name: build 312
      run: |
        nix build '.#${{ inputs.attribute }}.312' -o ./result
        cp ./result/*.whl ./dist/

    - name: build 313
      run: |
        nix build '.#${{ inputs.attribute }}.313' -o ./result
        cp ./result/*.whl ./dist/

    - name: build 314
      run: |
        nix build '.#${{ inputs.attribute }}.314' -o ./result
        cp ./result/*.whl ./dist/

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # @v4
      with:
        name: ${{ inputs.os }}_${{ inputs.attribute }}_gdb
        retention-days: 90
        path: ./dist/*

#    - name: Publish package distributions to PyPI
#      run: |
#        nix run nixpkgs#uv -- tool run twine upload dist/*
